version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: ./sw-backend
      dockerfile: Dockerfile
    container_name: django_container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    ports:
      - "8000:8000"

  angular:
    build:
      context: ./sw-frontend
      dockerfile: Dockerfile
    container_name: angular_container
    ports:
      - "4200:4200"
    depends_on:
      - django

volumes:
  postgres_data: